services:
  tardigrade:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: ${IMAGE:-tardigrade-foxy}
    container_name: ${NAME:-tardigrade-foxy}
    working_dir: /ws
    stdin_open: true
    tty: true
    environment:
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-0}
      RMW_IMPLEMENTATION: ${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}
    volumes:
      - ${WORKSPACE:-..}:/ws
    command: bash
